cargo-features = ["edition"]

[package]
name = "weecord"
version = "0.1.0"
authors = ["Porter Smith <flowbish@gmail.com>", "khyperia <khyperia@live.com>", "Noskcaj <kcajdev@gmail.com>"]
build = "build.rs"
edition = "2018"

[build-dependencies]
gcc = "0.3.54"
pkg-config = "0.3.11"

[lib]
name = "weecord"
crate-type = ["dylib"]

[dependencies]
libc = "0.2.42"
lazy_static = "1.0.2"

[dependencies.serenity]
git = "https://github.com/terminal-discord/serenity"
default_features = false
features = [
    "builder",
    "cache",
    "client",
    "gateway",
    "model",
    "http",
    "utils"
]

[dependencies.parsing]
path = "parsing"
