[package]
name = "weecord"
version = "0.1.0"
authors = ["Porter Smith <flowbish@gmail.com>", "khyperia <khyperia@live.com>", "Noskcaj <kcajdev@gmail.com>"]
build = "build.rs"

[build-dependencies]
gcc = "0.3.54"
pkg-config = "0.3.11"

[lib]
name = "weecord"
crate-type = ["dylib"]

[dependencies]
libc = "0.2.42"
serenity = { git = "https://github.com/Noskcaj19/serenity" }
lazy_static = "1.0.2"

[dependencies.parsing]
path = "parsing"

[dependencies.weechat-lib]
path = "weechat-lib"